baseURL = "https://re3turn.github.io/blog/"
DefaultContentLanguage = "en"
title = "return 3"
theme = "beautifulhugo"
canonifyurls = true
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-44827617-3"

[Params]
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true

[Author]
  name = "re3turn"
  email = "re3turn@gmail.com"
  github = "re3turn"
  twitter = "re3turn"
  spotify = "re3turn"
  telegram = "re3turn"

[staticmanr]
    api = "https://api.staticman.net/v2/entry/re3turn/blog/master/comments"
    pulls = "https://github.com/re3turn/blog/pulls"
    [staticmanr.recaptcha]
      sitekey = "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"
      secret = "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9LshissvNcYFfC/b8KKb4deH4V1+oqJEk/JcoK6jp6Rr2nZV4rjDP9M7nunC3WR5UGwMIYb8kKhur9pAic="

